// Objective-C API for talking to test/testgo/src/not.expert/test Go package.
//   gobind -lang=objc test/testgo/src/not.expert/test
//
// File is generated by gobind. Do not edit.

#ifndef __Test_H__
#define __Test_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull TestGreeting(NSString* _Nullable name);

#endif
